# Generated by Django 5.0.4 on 2024-05-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_productsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.FloatField(blank=True, max_length=200)),
                ('reduction', models.FloatField(blank=True, max_length=200)),
                ('new', models.FloatField(max_length=200)),
                ('boutique', models.CharField(default='', max_length=200)),
                ('image', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Computers', 'Computers'), ('Food', 'Food'), ('Kids', 'Kids'), ('Home', 'Home')], default='', max_length=40),
        ),
    ]
