# Generated by Django 5.0.4 on 2024-05-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productoutside_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Computers', 'Computers'), ('electronics', 'Electronics'), ('jewelery', 'Jewelery'), ("men's clothing", 'Men S Clothing'), ("women's clothing", 'Women S Clothing')], default='', max_length=40),
        ),
    ]
